Feature/societree
recursivezero/assignment pull request #12
Opened 2024-09-17 16:01 UTC by VamilP

Society Tree Visualizer: The tool should represent a caste family tree with 72 nodes, where each node represents a primary family branch. Upon clicking on a node, it should expand to show the surnames associated with that branch, along with their respective deity and gotra information.

This JSON file contains information about different branches of Indian families, their Gotras (ancestral lineage), associated deities, and common surnames. Each entry includes:

Branch Name: The name of the family branch.
Gotra: The ancestral lineage associated with the branch.
Deity: The deity that the branch worships.
Surnames: A list of common surnames associated with the branch.

2024-09-18 04:00 UTC, recursivezero requested changes

2024-09-18 04:00 UTC, recursivezero commented on src/lang1.json
add one node which have more than 20 surnames and one with 0 nodes  and display it.

2024-09-18 04:00 UTC, recursivezero commented on src/script.js
> +        <div class="surname-node">
use **details** and **summary** tag which have automatic close open feature. no need to done using js

2024-09-18 04:00 UTC, recursivezero commented on src/style.css
> +@font-face {
create assets/fonts folder and put font there and use that location

2024-09-18 04:00 UTC, recursivezero commented on src/README.md
Add how to start the project?

2024-12-01 04:32 UTC, xkeshav commented
resolve this conflicts and is that new PR?

2024-12-14 16:24 UTC, recursivezero commented
resolve the conflicts

2024-12-23 04:19 UTC, merged